# 文件路径: .github/workflows/build-windows-exe.yml
# 【PowerShell 语法修正版】 - 将CMD的换行符(^)替换为PowerShell的换行符(`)

name: Build X-AnyLabeling for Windows (Complete)

on:
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Run PyInstaller (with all resources)
        # 【重要修正】: 下面的多行命令使用了 PowerShell 的换行符 (`)
        run: |
          pyinstaller --noconfirm --onedir --clean `
          --windowed `
          --name "BacteriaLabelingTool" `
          --icon "anylabeling/resources/images/icon.ico" `
          --add-data "models;models" `
          --add-data "anylabeling/services/auto_labeling/bacteria_autoseg.yaml;anylabeling/services/auto_labeling" `
          --add-data "anylabeling/configs/auto_labeling;anylabeling/configs/auto_labeling" `
          --add-data "anylabeling/configs;anylabeling/configs" `
          --add-data "anylabeling/views/labeling/widgets/auto_labeling/auto_labeling.ui;anylabeling/views/labeling/widgets/auto_labeling" `
          --add-data "anylabeling/services/auto_labeling/configs/bert;anylabeling/services/auto_labeling/configs/bert" `
          --add-data "anylabeling/services/auto_labeling/configs/clip;anylabeling/services/auto_labeling/configs/clip" `
          --add-data "anylabeling/services/auto_labeling/configs/ppocr;anylabeling/services/auto_labeling/configs/ppocr" `
          --add-data "anylabeling/services/auto_labeling/configs/ram;anylabeling/services/auto_labeling/configs/ram" `
          anylabeling/app.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: dist/BacteriaLabelingTool
