# 文件路径: .github/workflows/build-windows-exe.yml
# 【Git LFS 修正版】 - 增加了 LFS 参数来拉取真实的模型大文件

name: Build X-AnyLabeling for Windows (Complete)

on:
  workflow_dispatch:

jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      # 【重要修正】: 在 checkout 步骤中增加了 lfs: true 和 fetch-depth: 0
      - name: Checkout repository with LFS
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Run PyInstaller (Single-Line Command)
        run: >
          pyinstaller --noconfirm --onedir --clean --console --name "BacteriaLabelingTool" --icon "anylabeling/resources/images/icon.ico" --add-data "models;models" --add-data "anylabeling/configs/auto_labeling/bacteria_autoseg.yaml;anylabeling/configs/auto_labeling" --add-data "anylabeling/configs/auto_labeling;anylabeling/configs/auto_labeling" --add-data "anylabeling/configs;anylabeling/configs" --add-data "anylabeling/views/labeling/widgets/auto_labeling/auto_labeling.ui;anylabeling/views/labeling/widgets/auto_labeling" --add-data "anylabeling/services/auto_labeling/configs/bert;anylabeling/services/auto_labeling/configs/bert" --add-data "anylabeling/services/auto_labeling/configs/clip;anylabeling/services/auto_labeling/configs/clip" --add-data "anylabeling/services/auto_labeling/configs/ppocr;anylabeling/services/auto_labeling/configs/ppocr" --add-data "anylabeling/services/auto_labeling/configs/ram;anylabeling/services/auto_labeling/configs/ram" anylabeling/app.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: dist/BacteriaLabelingTool
